config/routes.rb
JobSeeker::Application.routes.draw do
  resources :jobs
  resources :job_updates do
    member do
      post 'upload'
    end
  end

  post "signin", to: 'sessions#create', as: "signin"
  delete "signout", to: 'sessions#destroy', as: "signout"

  root 'home#index'

end

app/models/guest_user.rb
# == Schema Information
#
# Table name: guest_users
#
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#

class GuestUser < ActiveRecord::Base
  def name
    "Guest"
  end
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id             :integer          not null, primary key
#  company_name   :string(255)
#  position_title :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  user_id        :integer
#

class Job < ActiveRecord::Base
  has_many :job_updates
  has_one :last_update, -> { order("created_at DESC") }, class_name: "JobUpdate"
  belongs_to :user, class_name: "GuestUser"

  scope :by_user, -> (user) {
    where(user_id: user.id)
  }

  validates :company_name, :position_title, presence: true

  # create a new job, using bob if bob_listing_url is provided
  # (discards other arguments then)
  def self.from_bob(url)
    begin
      bob_job = Bob.fetch(url)
      new({
            position_title: bob_job.name,
            company_name: bob_job.company_name,
          })
    rescue Bob::UnprocessableHostError => e
      job = new
      job.errors.add(:base, e)
      job
    end
  end
end

app/models/job_update.rb
# == Schema Information
#
# Table name: job_updates
#
#  id          :integer          not null, primary key
#  description :text
#  job_id      :integer
#  created_at  :datetime
#  updated_at  :datetime
#  asset       :string(255)
#

class JobUpdate < ActiveRecord::Base
  mount_uploader :asset, AssetUploader
  belongs_to :job, touch: true

  validates :description, :job, presence: true

  scope :by_job, -> (job) {
    where(job_id: job.id)
  }

  scope :newest_first, -> {
    order("created_at DESC")
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def require_signed_in
    redirect_to root_path unless current_user
  end

  def current_user
    @current_user ||= begin
      session[:user_id] and GuestUser.find(session[:user_id])
    end
  end
  helper_method :current_user
end

app/controllers/concerns/angular_controller.rb
module AngularController
  extend ActiveSupport::Concern

  included do
    respond_to :html, :json
    around_action :without_root_in_json
  end

  def without_root_in_json
    ActiveRecord::Base.include_root_in_json = false
    yield
    ActiveRecord::Base.include_root_in_json = true
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to jobs_path
    end
  end
end

app/controllers/job_updates_controller.rb
class JobUpdatesController < ApplicationController
  include AngularController

  before_action :require_signed_in
  before_action :fetch_job_update, only: [:upload, :destroy]
  before_action :check_user, only: [:upload, :destroy]

  def index
    job = Job.by_user(current_user).find(params[:job_id])
    @job_updates = JobUpdate.by_job(job).newest_first
  end

  def create
    job = Job.by_user(current_user).find(params[:job_id])
    @job_update = JobUpdate.by_job(job).create!(params.permit(:description, :asset))
  end

  def upload
    @job_update.asset = params[:asset]
    @job_update.save!
  end

  def destroy
    @job_update.destroy
    head :ok
  end

  private
  def fetch_job_update
    @job_update = JobUpdate.find(params[:id])
  end

  def check_user
    head :unautharized and return if @job_update.job.user != current_user
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :require_signed_in
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.includes(:last_update).by_user(current_user)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    options = job_params
    if options[:bob_listing_url]
      @job = Job.by_user(current_user).from_bob(options[:bob_listing_url])
    else
      @job = Job.by_user(current_user).new(options)
    end

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job }
      else
        format.html { render action: 'new' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }

        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.by_user(current_user).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:company_name, :position_title, :bob_listing_url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = GuestUser.create!
    session[:user_id] = user.id
    flash[:success] = "Signed in as #{user.name}!"
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Signed out."
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/job_updates_helper.rb
module JobUpdatesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<% content_for :title do %>
  Welcome to JoBo
<% end -%>
<% content_for :header do %>
  <h1>Welcome to JoBo</h1>
<% end -%>

<div class="product-description">
  <div class="row">
    <div class="large-4 columns">
      <%= image_tag "hero-1.jpg" %>
    </div>
    <div class="large-8 columns">
      <p>Found an interesting job posting you don't want to forget about?</p>
      <p>Maybe you already started making a list of your next career steps.</p>
      <p>JoBo is the place where you can keep that list organized.</p>
    </div>
  </div>

  <div class="row">
    <div class="large-8 columns">
      <p>Every job you create has its own timeline of updates.</p>
      <p>Whenever you communicate with the recruiter just make a new note about the important stuff you discussed about.</p>
      <p>During the later stages, keep track of your interview dates and any tasks you have to complete.</p>
    </div>
    <div class="large-4 columns">
      <%= image_tag "hero-2.jpg" %>
    </div>
  </div>
</div>

<p class="align-center">
  <%= link_to "Sign in as a guest and start using JoBo!", signin_path, method: :post, class: "button" %>
</p>

app/views/jobs/_form.html.erb
<%= simple_form_for @job do |f| %>
  <%= f.input :company_name %><br>
  <%= f.input :position_title %>
  <%= f.button :submit %>
<% end %>

app/views/jobs/_job.html.erb
<li>
  <div class="job">
    <h4>
      <%= job.company_name %> <br/>
      <small><%= job.position_title %></small>
    </h4>
    <div class="last-update">
      <% if job.last_update %>
        <div class="time">
          Last updated
          <%= distance_of_time_in_words_to_now job.last_update.created_at %>
          ago
        </div>
        <p><%= job.last_update.description %></p>
      <% else %>
        <div class="panel">
          <h5>No updates yet</h5>
          Start adding updates from the <%= link_to 'job page', job %>.
        </div>
      <% end -%>
    </div>
    <div>
      <%= link_to 'Show', job, class: 'tiny button' %>
      <%= link_to 'Edit', edit_job_path(job), class: 'tiny button secondary' %>
      <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' }, class: 'tiny button secondary' %>
    </div>
  </div>
</li>

app/views/jobs/_new_from_url.html.erb
<%= form_tag(jobs_path, method: 'POST',
             'ng-submit' => 'createFromURL(url)') do %>
  <fieldset>
    <legend>Create a job from a URL</legend>

    <input type="url" name="job[bob_listing_url]"
           value=""
           ng-bind="url"
           placeholder="http://jobs.github.com/">
    <button type="submit" name="create_job_from_url">Create</button>
  </fieldset>
<%- end -%>

app/views/jobs/edit.html.erb
<% content_for :title do %>
  Editing job
<% end -%>
<% content_for :header do %>
  <h1>Editing job</h1>
<% end -%>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<% content_for :title do %>
  Listing jobs
<% end -%>
<% content_for :header do %>
  <h1>
    Listing jobs
    <small><%= link_to 'New job', new_job_path %></small>
  </h1>
<% end -%>

<%= render 'jobs/new_from_url' %>

<ul class="jobs large-block-grid-3 small-block-grid-1">
  <%= render @jobs %>
</ul>

app/views/jobs/new.html.erb
<% content_for :title do %>
  New job
<% end -%>
<% content_for :header do %>
  <h1>New job</h1>
<% end -%>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<% content_for :title do %>
  <%= @job.company_name %> - <%= @job.position_title %>
<% end -%>
<% content_for :header do %>
  <h1>
    <%= @job.company_name %>
    <small><%= @job.position_title %></small>
  </h1>
<% end -%>

<% if notice %>
  <p class="alert-box success"><%= notice %></p>
<% end -%>

<div>
  <%= link_to 'Edit job', edit_job_path(@job), class: "secondary small button" %>
  <%= link_to 'Back to list', jobs_path, class: "secondary small button" %>
</div>

<div ng-app="blang">
  <div ng-controller="JobUpdateCtrl" data-job-id="<%= @job.id %>">
    <form ng-submit="add()" action="" class="new-job-update">
      <fieldset>
        <legend>New job update</legend>
        <div class="row">
          <div class="large-10 columns">
            <input ng-model="jobUpdate.description" type="text" placeholder="Description" required/>
          </div>
          <div class="large-2 columns">
            <input class="small button expand" type="submit" value="Create"/>
          </div>
        </div>
      </fieldset>
    </form>

    <div class="job-updates">
      <div class="job-update" ng-repeat="jobUpdate in jobUpdates">
        <div class="row">
          <div class="small-6 columns created-at">
            <small class="relative">{{ jobUpdate.relative_created_at }}</small>
            <small class="absolute">{{ jobUpdate.absolute_created_at }}</small>
          </div>
          <div class="small-6 columns align-right">
            <button class="tiny button secondary" ng-click="delete($index)">Destroy</button>
          </div>
        </div>
        <div class="row">
          <div class="small-12 columns">
            <p>{{ jobUpdate.description }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <div class="row">
      <div class="large-4 push-8 align-right columns">
        <% if current_user %>
          Welcome, <%= current_user.name %>!
          <%= link_to "Sign out", signout_path, method: :delete, class: "small secondary button" %>
        <% else %>
          <%= link_to "Sign in as Guest", signin_path, method: :post, class: "small button" %>
        <% end -%>
      </div>
      <div class="large-8 pull-4 columns">
        <%= yield :header %>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <%= yield %>
      </div>
    </div>

    <div class="space-for-vote-banner"></div>
    <script type="text/javascript">
      var rumbleBannerBackgroundColor = "#2ba6cb";
      var rumbleBannerTextColor = "#ddd";
      var rumbleBannerLinkColor = "#fff";

      var rumbleBannerPlacement = "bottom";
    </script>
    <script src="http://s0.railsrumble.com/banner.js" type="text/javascript"></script>
  </body>
</html>